(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(setq default-buffer-file-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq file-name-coding-system 'utf-8)
(setq default-file-name-coding-system 'utf-8)
(setq process-coding-system-alist '((".*" . utf-8)))
(set-language-environment "UTF-8")
(if *is_window*
  (setq w32-unicode-filenames t))

(setq make-backup-files nil)
(setq auto-save-default nil)
(setq create-lockfiles nil) 
(setq default-buffer-file-coding-system 'utf)
(setq gc-cons-threshold most-positive-fixnum)
(setq-default tab-width 8)
(setq tab-always-indent nil)
(provide 'base_start)
